### ISSUE TITLE
NLog dependency uses non-existent NLog version '5.0.0-beta11'

### ISSUE THREAD

**Issue by frizzr** [infinispan/dotnet-client#155]
https://github.com/infinispan/dotnet-client/blob/749b031563e4c32541154fb49df5bf6a2b6659d5/src/Infinispan.HotRod/Infinispan.HotRod.csproj#L17

NLog does not have a version '5.0.0-beta11' available on nuget.org and that version is not listed anywhere on the NLog project Github site.

Because of this, we see errors when using this NuGet package referring to the missing NLog dependency.

Could we get this changed to a valid NLog version, like 4.7.3?

**Comment by snakefoot** [comment]
Any chance for an updated nuget-package:

https://www.nuget.org/packages/Infinispan.HotRod
