### ISSUE TITLE
SWIG interface RemoteByteArrayCache conflicts with EntityFrameworkCore context

### ISSUE THREAD

**Issue by arquitecturatic** [infinispan/dotnet-client#168]
I am using hot rod client inside a business logic that uses a DbContext of EntityFrameworkCore and I am getting "System.ExecutionEngineException" at RemoteByteArrayCache class. 

Portion of code where the exception is thrwon.
```
public VectorByte query(VectorByte qr, uint size) {
    VectorByte ret = new VectorByte(hotrodcsPINVOKE.RemoteByteArrayCache_query(swigCPtr, VectorByte.getCPtr(qr), size), true);
    if (hotrodcsPINVOKE.SWIGPendingException.Pending) throw hotrodcsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }
```

Exception details:
```
System.ExecutionEngineException
  HResult=0x80131506
  Origen = <No se puede evaluar el origen de la excepción>
  Seguimiento de la pila:
<No se puede evaluar el seguimiento de la pila de excepciones>

```

Steps to reproduce the error:
1. Create a instance of DbContext
2. Create a intance of IRemoteCache
3. Initialize DbContext getting any data.
4. Try to get any entity of cache with Get method (it's working)
5. Try to get some entities with query (throws exception)

Thanks.

**Comment by rigazilla** [comment]
Hi @arquitecturatic the error reported is pretty generic:
-  is the client correctly configured? i.e. is it working without the EFC ?
- how do you integrated the client with the EFC? we don't provide the integration layer atm
